### PR TITLE
Replace git shortlog output parsing code with a RegExp

### PR DESCRIPTION
**Pull request by manrueda**
The current solution to parse the output of the `git shortlog` command is based on splits, `EOL` and character findings. I replace it with a regular expression that parse the `git shortlog -sne` output format and extracts all the key pieces from it (number of commits, name, email, etc).

The main problem with the current solution was that was based on the OS `EOL` definition and that is not reliable because on windows you can use different terminals (cmd, gitbash, etc) and the result is not split correctly by line.

Using regular expressions in this way will ensure that the output will be parsed correctly.

> There are changes in some code that is unrelated to my change, looks like is `prettier-standard` changing code.

### CODE REVIEW

**Comment by Kikobeats** [comment]
oh, thanks for that, it's very valuable!

How do you test it? the project doesn't have tests and that's my fault. Do you think we can do something in that aspect to be sure the output is still the same?

**Comment by manrueda** [comment]
I test it on Windows 10, macOS and a docker container with a debian based image. I was thinking to add some CI tests. Travis supports macos, linux and windows now.

**Comment by Kikobeats** [comment]
Tested on local, looks fine! Thanks for that

**Comment by Kikobeats** [comment]
Feel totally free open a new PR for adding tests 🙂

**Pull request merged**
